/* =============================================================
   EXPRESIONES Y FRASES (versión España)
   - FRASES: frase del día en la parte superior (inglés y español).
   - EXPRESIONES: 125 por estación (500 en total). Cada día se muestran
     12 seguidas de la estación actual; al acabar la lista vuelve a empezar.
   Para añadir una: { en: "...", es: "..." },  (respeta comas y comillas)
   ============================================================= */

window.FRASES = [
  { en: "We're so proud of you.", es: "Estamos muy orgullosos de ti." },
  { en: "You've got this.", es: "Tú puedes con esto." },
  { en: "Thinking of you today.", es: "Hoy pensamos en ti." },
  { en: "Distance means so little when someone means so much.", es: "La distancia importa poco cuando alguien importa tanto." },
  { en: "Every day is one day closer.", es: "Cada día es un día menos." },
  { en: "Be brave, be kind, be you.", es: "Sé valiente, sé buena, sé tú." },
  { en: "Home is wherever you are loved.", es: "Tu casa está donde te quieren." },
  { en: "Enjoy every moment of this adventure.", es: "Disfruta cada momento de esta aventura." },
  { en: "You make us smile from far away.", es: "Nos haces sonreír desde lejos." },
  { en: "Small steps every day.", es: "Pequeños pasos cada día." },
  { en: "We miss you, and we're cheering for you.", es: "Te echamos de menos y te animamos desde aquí." },
  { en: "Trust yourself. You know more than you think.", es: "Confía en ti. Sabes más de lo que crees." },
  { en: "It's okay to have a hard day.", es: "Está bien tener un día difícil." },
  { en: "Keep being curious.", es: "Sigue siendo curiosa." },
  { en: "Today is a good day to learn something new.", es: "Hoy es un buen día para aprender algo nuevo." },
  { en: "You are stronger than you know.", es: "Eres más fuerte de lo que crees." },
  { en: "Sending you a big hug across the ocean.", es: "Te mandamos un abrazo enorme al otro lado del océano." },
  { en: "Be proud of how far you've come.", es: "Siéntete orgullosa de lo lejos que has llegado." },
  { en: "Make today count.", es: "Haz que hoy cuente." },
  { en: "Smile, it suits you.", es: "Sonríe, te queda genial." },
  { en: "One day at a time.", es: "Día a día." },
  { en: "You belong wherever you choose to shine.", es: "Encajas allí donde decides brillar." },
  { en: "Say yes to new things.", es: "Di que sí a cosas nuevas." },
  { en: "Mistakes mean you're trying.", es: "Equivocarse significa que lo estás intentando." },
  { en: "We love you to the moon and back.", es: "Te queremos hasta la luna y vuelta." },
  { en: "Take care of yourself today.", es: "Cuídate hoy." },
  { en: "Your courage inspires us.", es: "Tu valentía nos inspira." },
  { en: "Good things are coming.", es: "Vienen cosas buenas." },
  { en: "Call us whenever you want. Always.", es: "Llámanos cuando quieras. Siempre." },
  { en: "The best stories start far from home.", es: "Las mejores historias empiezan lejos de casa." }
];

/* =============================================================
   PALABRAS DE LA ESTACIÓN (cambian solas según el mes)
   otoño: sep-nov · invierno: dic-feb · primavera: mar-may · verano: jun-ago
   ============================================================= */

window.EXPRESIONES = {
  /* ---------- Primavera (marzo a mayo) ---------- */
  primavera: [
    { en: "Spring", es: "Primavera" },
    { en: "Blossom", es: "Flor de árbol frutal" },
    { en: "Almond blossom", es: "Flor del almendro" },
    { en: "Cherry blossom", es: "Flor del cerezo" },
    { en: "To bloom", es: "Florecer" },
    { en: "In full bloom", es: "En plena floración" },
    { en: "Bud", es: "Capullo, yema" },
    { en: "To sprout", es: "Brotar" },
    { en: "Green shoots", es: "Brotes verdes" },
    { en: "Daisy", es: "Margarita" },
    { en: "Poppy", es: "Amapola" },
    { en: "Tulip", es: "Tulipán" },
    { en: "Daffodil", es: "Narciso" },
    { en: "Lilac", es: "Lila" },
    { en: "Rose bush", es: "Rosal" },
    { en: "Bouquet", es: "Ramo de flores" },
    { en: "Wildflowers", es: "Flores silvestres" },
    { en: "Meadow", es: "Prado" },
    { en: "Fresh grass", es: "Hierba fresca" },
    { en: "Bee", es: "Abeja" },
    { en: "Butterfly", es: "Mariposa" },
    { en: "Ladybird / Ladybug", es: "Mariquita" },
    { en: "Caterpillar", es: "Oruga" },
    { en: "Ant", es: "Hormiga" },
    { en: "Snail", es: "Caracol" },
    { en: "Frog", es: "Rana" },
    { en: "Tadpole", es: "Renacuajo" },
    { en: "Lizard", es: "Lagartija" },
    { en: "Swallow", es: "Golondrina" },
    { en: "Stork", es: "Cigüeña" },
    { en: "Nest", es: "Nido" },
    { en: "Birdsong", es: "Canto de los pájaros" },
    { en: "Lamb", es: "Cordero" },
    { en: "Dew", es: "Rocío" },
    { en: "Mud", es: "Barro" },
    { en: "To mow the lawn", es: "Cortar el césped" },
    { en: "To plant", es: "Plantar" },
    { en: "Seeds", es: "Semillas" },
    { en: "Flowerpot", es: "Maceta" },
    { en: "Window box", es: "Jardinera" },
    { en: "Watering can", es: "Regadera" },
    { en: "Hose", es: "Manguera" },
    { en: "Greenhouse", es: "Invernadero" },
    { en: "Vegetable garden", es: "Huerto" },
    { en: "To water the plants", es: "Regar las plantas" },
    { en: "Pollen", es: "Polen" },
    { en: "Hay fever", es: "Alergia al polen" },
    { en: "To sneeze", es: "Estornudar" },
    { en: "Itchy eyes", es: "Picor de ojos" },
    { en: "Antihistamine", es: "Antihistamínico" },
    { en: "Spring fatigue", es: "Astenia primaveral" },
    { en: "April showers", es: "Lluvias de abril" },
    { en: "Rainbow", es: "Arcoíris" },
    { en: "Thunderstorm", es: "Tormenta" },
    { en: "Mild weather", es: "Tiempo suave" },
    { en: "Breeze", es: "Brisa" },
    { en: "Sunny spells", es: "Intervalos de sol" },
    { en: "Changeable weather", es: "Tiempo cambiante" },
    { en: "Thaw", es: "Deshielo" },
    { en: "Melting snow", es: "Nieve derritiéndose" },
    { en: "Longer days", es: "Días más largos" },
    { en: "Sunrise", es: "Amanecer" },
    { en: "The clocks go forward", es: "Se adelanta la hora" },
    { en: "Spring equinox", es: "Equinoccio de primavera" },
    { en: "Light jacket", es: "Chaqueta ligera" },
    { en: "Denim jacket", es: "Cazadora vaquera" },
    { en: "Trainers / Sneakers", es: "Zapatillas de deporte" },
    { en: "Short sleeves", es: "Manga corta" },
    { en: "Pastel colours", es: "Colores pastel" },
    { en: "Lighter clothes", es: "Ropa más ligera" },
    { en: "To put away winter clothes", es: "Guardar la ropa de invierno" },
    { en: "Spring cleaning", es: "Limpieza a fondo" },
    { en: "To declutter", es: "Ordenar y quitar trastos" },
    { en: "Lent", es: "Cuaresma" },
    { en: "Palm Sunday", es: "Domingo de Ramos" },
    { en: "Holy Week", es: "Semana Santa" },
    { en: "Easter", es: "Pascua" },
    { en: "Easter Sunday", es: "Domingo de Resurrección" },
    { en: "Procession", es: "Procesión" },
    { en: "Easter egg", es: "Huevo de Pascua" },
    { en: "Easter bunny", es: "Conejo de Pascua" },
    { en: "French toast", es: "Torrija" },
    { en: "Easter holidays", es: "Vacaciones de Semana Santa" },
    { en: "Father's Day", es: "Día del Padre" },
    { en: "Mother's Day", es: "Día de la Madre" },
    { en: "World Book Day", es: "Día del Libro" },
    { en: "Labour Day", es: "Día del Trabajo" },
    { en: "April Fools' Day", es: "Día de las bromas (1 de abril)" },
    { en: "Prank", es: "Broma" },
    { en: "Fair", es: "Feria" },
    { en: "First communion", es: "Primera comunión" },
    { en: "Wedding season", es: "Temporada de bodas" },
    { en: "Picnic", es: "Comida en el campo" },
    { en: "Day trip", es: "Excursión de un día" },
    { en: "Bike ride", es: "Paseo en bici" },
    { en: "Hiking", es: "Senderismo" },
    { en: "Terrace", es: "Terraza" },
    { en: "To have a drink outside", es: "Tomar algo en una terraza" },
    { en: "Final exams", es: "Exámenes finales" },
    { en: "To revise", es: "Repasar" },
    { en: "Study plan", es: "Plan de estudio" },
    { en: "Final project", es: "Trabajo final" },
    { en: "University entrance exam", es: "Selectividad" },
    { en: "Application form", es: "Solicitud" },
    { en: "Graduation ceremony", es: "Ceremonia de graduación" },
    { en: "Prom", es: "Baile de fin de curso" },
    { en: "Yearbook", es: "Anuario" },
    { en: "Fresh strawberries", es: "Fresas frescas" },
    { en: "Asparagus", es: "Espárragos" },
    { en: "Artichoke", es: "Alcachofa" },
    { en: "Broad beans", es: "Habas" },
    { en: "Peas", es: "Guisantes" },
    { en: "Cherries", es: "Cerezas" },
    { en: "Loquat", es: "Níspero" },
    { en: "Butterflies in my stomach", es: "Mariposas en el estómago" },
    { en: "A spring in your step", es: "Ir con energía y alegría" },
    { en: "To turn over a new leaf", es: "Pasar página" },
    { en: "Every cloud has a silver lining", es: "No hay mal que por bien no venga" },
    { en: "Fresh as a daisy", es: "Fresco como una rosa" },
    { en: "Rain or shine", es: "Llueva o haga sol" },
    { en: "Bright colours", es: "Colores vivos" },
    { en: "To feel refreshed", es: "Sentirse renovado" },
    { en: "Sunny day", es: "Día soleado" },
    { en: "To stretch your legs", es: "Estirar las piernas" },
    { en: "To soak up the sun", es: "Disfrutar del sol" }
  ],
  /* ---------- Verano (junio a agosto) ---------- */
  verano: [
    { en: "Summer", es: "Verano" },
    { en: "Summer holidays", es: "Vacaciones de verano" },
    { en: "Heatwave", es: "Ola de calor" },
    { en: "Scorching hot", es: "Calor abrasador" },
    { en: "Muggy", es: "Bochornoso" },
    { en: "It's boiling", es: "Hace un calor horrible" },
    { en: "The dog days of summer", es: "La canícula" },
    { en: "To sweat", es: "Sudar" },
    { en: "Sunstroke", es: "Insolación" },
    { en: "Heatstroke", es: "Golpe de calor" },
    { en: "Sunburn", es: "Quemadura solar" },
    { en: "Sunscreen", es: "Protector solar" },
    { en: "After-sun lotion", es: "Crema aftersun" },
    { en: "Stay hydrated", es: "Mantente hidratado" },
    { en: "Water bottle", es: "Botella de agua" },
    { en: "To cool off", es: "Refrescarse" },
    { en: "In the shade", es: "A la sombra" },
    { en: "Fan", es: "Ventilador" },
    { en: "Air conditioning", es: "Aire acondicionado" },
    { en: "Sunglasses", es: "Gafas de sol" },
    { en: "Sun hat", es: "Sombrero de sol" },
    { en: "Flip-flops", es: "Chanclas" },
    { en: "Sandals", es: "Sandalias" },
    { en: "Swimsuit", es: "Bañador" },
    { en: "Bikini", es: "Biquini" },
    { en: "Beach towel", es: "Toalla de playa" },
    { en: "Beach umbrella", es: "Sombrilla" },
    { en: "Sunbed", es: "Tumbona" },
    { en: "Beach bag", es: "Bolsa de playa" },
    { en: "Cool box", es: "Nevera portátil" },
    { en: "Sand", es: "Arena" },
    { en: "Sandcastle", es: "Castillo de arena" },
    { en: "Bucket and spade", es: "Cubo y pala" },
    { en: "Seashell", es: "Concha" },
    { en: "Wave", es: "Ola" },
    { en: "Tide", es: "Marea" },
    { en: "High tide / Low tide", es: "Marea alta / marea baja" },
    { en: "Shore", es: "Orilla" },
    { en: "Cove", es: "Cala" },
    { en: "Cliff", es: "Acantilado" },
    { en: "Lighthouse", es: "Faro" },
    { en: "Pier", es: "Muelle" },
    { en: "Crystal-clear water", es: "Agua cristalina" },
    { en: "Sea breeze", es: "Brisa marina" },
    { en: "Jellyfish", es: "Medusa" },
    { en: "Lifeguard", es: "Socorrista" },
    { en: "Red flag", es: "Bandera roja" },
    { en: "To go for a swim", es: "Darse un baño" },
    { en: "To sunbathe", es: "Tomar el sol" },
    { en: "To get a tan", es: "Ponerse moreno" },
    { en: "Tan lines", es: "Marcas del bañador" },
    { en: "Freckles", es: "Pecas" },
    { en: "Swimming pool", es: "Piscina" },
    { en: "To dive in", es: "Tirarse de cabeza" },
    { en: "Snorkel", es: "Tubo de buceo" },
    { en: "Swimming goggles", es: "Gafas de natación" },
    { en: "Water park", es: "Parque acuático" },
    { en: "Pool party", es: "Fiesta en la piscina" },
    { en: "Ice cream", es: "Helado" },
    { en: "Ice lolly / Popsicle", es: "Polo" },
    { en: "Slushie", es: "Granizado" },
    { en: "Tiger nut milk", es: "Horchata" },
    { en: "Cold tomato soup", es: "Gazpacho" },
    { en: "Watermelon", es: "Sandía" },
    { en: "Melon", es: "Melón" },
    { en: "Peach", es: "Melocotón" },
    { en: "Apricot", es: "Albaricoque" },
    { en: "Plum", es: "Ciruela" },
    { en: "Lemonade", es: "Limonada" },
    { en: "Iced coffee", es: "Café con hielo" },
    { en: "Barbecue", es: "Barbacoa" },
    { en: "Grilled sardines", es: "Sardinas a la brasa" },
    { en: "Seafood", es: "Marisco" },
    { en: "Beach bar", es: "Chiringuito" },
    { en: "Late dinner", es: "Cena tardía" },
    { en: "Afternoon nap", es: "Siesta" },
    { en: "Long summer evenings", es: "Largas tardes de verano" },
    { en: "Rooftop bar", es: "Terraza en la azotea" },
    { en: "Outdoor cinema", es: "Cine de verano" },
    { en: "Open-air concert", es: "Concierto al aire libre" },
    { en: "Music festival", es: "Festival de música" },
    { en: "Village fiesta", es: "Fiestas del pueblo" },
    { en: "Funfair rides", es: "Atracciones de feria" },
    { en: "Fireworks", es: "Fuegos artificiales" },
    { en: "Midsummer Night", es: "Noche de San Juan" },
    { en: "Summer solstice", es: "Solsticio de verano" },
    { en: "The longest day", es: "El día más largo" },
    { en: "Shooting star", es: "Estrella fugaz" },
    { en: "Starry sky", es: "Cielo estrellado" },
    { en: "The Perseids", es: "Las lágrimas de San Lorenzo" },
    { en: "Sunset", es: "Puesta de sol" },
    { en: "Mosquito bite", es: "Picadura de mosquito" },
    { en: "Insect repellent", es: "Repelente de insectos" },
    { en: "Wasp", es: "Avispa" },
    { en: "Cicada", es: "Cigarra" },
    { en: "Firefly", es: "Luciérnaga" },
    { en: "Thunder and lightning", es: "Truenos y relámpagos" },
    { en: "Drought", es: "Sequía" },
    { en: "Forest fire", es: "Incendio forestal" },
    { en: "Road trip", es: "Viaje en coche" },
    { en: "Traffic jam", es: "Atasco" },
    { en: "Holiday exodus", es: "Operación salida" },
    { en: "Suitcase", es: "Maleta" },
    { en: "To pack", es: "Hacer la maleta" },
    { en: "To unpack", es: "Deshacer la maleta" },
    { en: "Passport", es: "Pasaporte" },
    { en: "Boarding pass", es: "Tarjeta de embarque" },
    { en: "Carry-on bag", es: "Equipaje de mano" },
    { en: "Check-in desk", es: "Mostrador de facturación" },
    { en: "Delayed flight", es: "Vuelo retrasado" },
    { en: "Jet lag", es: "Desfase horario" },
    { en: "Souvenir", es: "Recuerdo" },
    { en: "Postcard", es: "Postal" },
    { en: "Campsite", es: "Camping" },
    { en: "Tent", es: "Tienda de campaña" },
    { en: "Sleeping bag", es: "Saco de dormir" },
    { en: "Hammock", es: "Hamaca" },
    { en: "Summer camp", es: "Campamento de verano" },
    { en: "Summer job", es: "Trabajo de verano" },
    { en: "Resit exams", es: "Recuperaciones" },
    { en: "To chill out", es: "Relajarse" },
    { en: "To hang out", es: "Pasar el rato" },
    { en: "Out of office", es: "Fuera de la oficina" },
    { en: "Summer fling", es: "Amor de verano" },
    { en: "Boat trip", es: "Paseo en barco" }
  ],
  /* ---------- Otoño (septiembre a noviembre) ---------- */
  otono: [
    { en: "Autumn / Fall", es: "Otoño" },
    { en: "Fallen leaves", es: "Hojas caídas" },
    { en: "To rake the leaves", es: "Rastrillar las hojas" },
    { en: "Chestnut", es: "Castaña" },
    { en: "Roasted chestnuts", es: "Castañas asadas" },
    { en: "Acorn", es: "Bellota" },
    { en: "Mushroom", es: "Seta" },
    { en: "To go mushroom picking", es: "Ir a coger setas" },
    { en: "Pumpkin", es: "Calabaza" },
    { en: "Harvest", es: "Cosecha" },
    { en: "Grape harvest", es: "Vendimia" },
    { en: "Vineyard", es: "Viñedo" },
    { en: "Pomegranate", es: "Granada" },
    { en: "Quince jelly", es: "Dulce de membrillo" },
    { en: "Persimmon", es: "Caqui" },
    { en: "Walnut", es: "Nuez" },
    { en: "Hazelnut", es: "Avellana" },
    { en: "Sweet potato", es: "Boniato" },
    { en: "Apple picking", es: "Recogida de manzanas" },
    { en: "Scarecrow", es: "Espantapájaros" },
    { en: "Squirrel", es: "Ardilla" },
    { en: "Hedgehog", es: "Erizo" },
    { en: "Migrating birds", es: "Aves migratorias" },
    { en: "Bare branches", es: "Ramas desnudas" },
    { en: "Foliage", es: "Follaje" },
    { en: "Golden leaves", es: "Hojas doradas" },
    { en: "Crunchy leaves", es: "Hojas crujientes" },
    { en: "Chilly", es: "Fresquito" },
    { en: "Crisp air", es: "Aire fresco y seco" },
    { en: "Drizzle", es: "Llovizna" },
    { en: "Downpour", es: "Chaparrón" },
    { en: "It's pouring down", es: "Está diluviando" },
    { en: "Overcast", es: "Cubierto, nublado" },
    { en: "Fog", es: "Niebla" },
    { en: "Mist", es: "Neblina" },
    { en: "Damp", es: "Húmedo" },
    { en: "Gust of wind", es: "Ráfaga de viento" },
    { en: "Windy", es: "Hace viento" },
    { en: "Puddle", es: "Charco" },
    { en: "Raincoat", es: "Chubasquero" },
    { en: "Umbrella", es: "Paraguas" },
    { en: "Rain boots / Wellies", es: "Botas de agua" },
    { en: "Sweater / Jumper", es: "Jersey" },
    { en: "Cardigan", es: "Chaqueta de punto" },
    { en: "Scarf", es: "Bufanda" },
    { en: "Trench coat", es: "Gabardina" },
    { en: "Corduroy", es: "Pana" },
    { en: "Ankle boots", es: "Botines" },
    { en: "Turtleneck", es: "Jersey de cuello alto" },
    { en: "Thick socks", es: "Calcetines gordos" },
    { en: "To layer up", es: "Ponerse varias capas" },
    { en: "Sweater weather", es: "Tiempo de jersey" },
    { en: "The days are getting shorter", es: "Los días se acortan" },
    { en: "The clocks go back", es: "Se atrasa la hora" },
    { en: "It gets dark early", es: "Anochece pronto" },
    { en: "Dusk", es: "Anochecer" },
    { en: "Back to school", es: "Vuelta al cole" },
    { en: "School supplies", es: "Material escolar" },
    { en: "Timetable", es: "Horario" },
    { en: "Homework", es: "Deberes" },
    { en: "Locker", es: "Taquilla" },
    { en: "Term", es: "Trimestre" },
    { en: "Midterm exam", es: "Examen parcial" },
    { en: "Deadline", es: "Fecha límite" },
    { en: "To catch up on", es: "Ponerse al día con" },
    { en: "To settle in", es: "Adaptarse, instalarse" },
    { en: "New routine", es: "Nueva rutina" },
    { en: "Back to work", es: "Vuelta al trabajo" },
    { en: "Post-holiday blues", es: "Síndrome postvacacional" },
    { en: "To get back into the swing of things", es: "Retomar el ritmo" },
    { en: "New school year", es: "Nuevo curso" },
    { en: "Extracurricular activities", es: "Actividades extraescolares" },
    { en: "Field trip", es: "Excursión del colegio" },
    { en: "Halloween", es: "Halloween" },
    { en: "Costume", es: "Disfraz" },
    { en: "Trick or treat", es: "Truco o trato" },
    { en: "Haunted house", es: "Casa encantada" },
    { en: "Spooky", es: "Espeluznante" },
    { en: "Witch", es: "Bruja" },
    { en: "Ghost", es: "Fantasma" },
    { en: "Skeleton", es: "Esqueleto" },
    { en: "Bat", es: "Murciélago" },
    { en: "Spider web", es: "Telaraña" },
    { en: "Carved pumpkin", es: "Calabaza tallada" },
    { en: "All Saints' Day", es: "Día de Todos los Santos" },
    { en: "Cemetery", es: "Cementerio" },
    { en: "Bonfire", es: "Hoguera" },
    { en: "Cosy / Cozy", es: "Acogedor" },
    { en: "To curl up on the sofa", es: "Acurrucarse en el sofá" },
    { en: "Hot drink", es: "Bebida caliente" },
    { en: "Pumpkin soup", es: "Crema de calabaza" },
    { en: "Stew", es: "Guiso" },
    { en: "Comfort food", es: "Comida reconfortante" },
    { en: "Baked apple", es: "Manzana asada" },
    { en: "Cinnamon", es: "Canela" },
    { en: "Herbal tea", es: "Infusión" },
    { en: "To catch a cold", es: "Resfriarse" },
    { en: "Runny nose", es: "Nariz que gotea" },
    { en: "Sore throat", es: "Dolor de garganta" },
    { en: "Flu jab / Flu shot", es: "Vacuna de la gripe" },
    { en: "Cough", es: "Tos" },
    { en: "Tissues", es: "Pañuelos de papel" },
    { en: "Under the weather", es: "Pachucho" },
    { en: "Hiking boots", es: "Botas de montaña" },
    { en: "Forest trail", es: "Sendero del bosque" },
    { en: "Deer rut", es: "Berrea del ciervo" },
    { en: "Moss", es: "Musgo" },
    { en: "Pine cone", es: "Piña de pino" },
    { en: "To turn on the heating", es: "Encender la calefacción" },
    { en: "Weather forecast", es: "Previsión del tiempo" },
    { en: "Long weekend", es: "Puente" },
    { en: "Bank holiday", es: "Día festivo" },
    { en: "Black Friday sales", es: "Rebajas de Black Friday" },
    { en: "To save up", es: "Ahorrar" },
    { en: "Autumn equinox", es: "Equinoccio de otoño" },
    { en: "Harvest moon", es: "Luna de la cosecha" },
    { en: "To stay in", es: "Quedarse en casa" },
    { en: "Board game", es: "Juego de mesa" },
    { en: "Movie night", es: "Noche de peli" },
    { en: "Rustling leaves", es: "Crujir de hojas" },
    { en: "Change of season", es: "Cambio de estación" },
    { en: "Wardrobe swap", es: "Cambio de armario" },
    { en: "To put away summer clothes", es: "Guardar la ropa de verano" },
    { en: "To fall behind", es: "Quedarse atrás, retrasarse" },
    { en: "To hit the books", es: "Ponerse a estudiar" }
  ],
  /* ---------- Invierno (diciembre a febrero) ---------- */
  invierno: [
    { en: "Winter", es: "Invierno" },
    { en: "Snow", es: "Nieve" },
    { en: "Snowflake", es: "Copo de nieve" },
    { en: "Snowfall", es: "Nevada" },
    { en: "Blizzard", es: "Ventisca" },
    { en: "Sleet", es: "Aguanieve" },
    { en: "Hail", es: "Granizo" },
    { en: "Frost", es: "Escarcha" },
    { en: "Frosty morning", es: "Mañana de escarcha" },
    { en: "Black ice", es: "Placas de hielo" },
    { en: "Icicle", es: "Carámbano" },
    { en: "Slippery", es: "Resbaladizo" },
    { en: "Below freezing", es: "Bajo cero" },
    { en: "It's freezing out there", es: "Fuera hace un frío que pela" },
    { en: "Wind chill", es: "Sensación térmica" },
    { en: "Cold snap", es: "Ola de frío" },
    { en: "To shiver", es: "Tiritar" },
    { en: "Numb fingers", es: "Dedos entumecidos" },
    { en: "Chapped lips", es: "Labios agrietados" },
    { en: "Goosebumps", es: "Piel de gallina" },
    { en: "Coat", es: "Abrigo" },
    { en: "Puffer jacket", es: "Plumas" },
    { en: "Gloves", es: "Guantes" },
    { en: "Mittens", es: "Manoplas" },
    { en: "Woolly hat / Beanie", es: "Gorro de lana" },
    { en: "Earmuffs", es: "Orejeras" },
    { en: "Thermal underwear", es: "Ropa térmica" },
    { en: "Snow boots", es: "Botas de nieve" },
    { en: "Slippers", es: "Zapatillas de casa" },
    { en: "Hot water bottle", es: "Bolsa de agua caliente" },
    { en: "Blanket", es: "Manta" },
    { en: "Duvet", es: "Edredón nórdico" },
    { en: "Fireplace", es: "Chimenea" },
    { en: "Radiator", es: "Radiador" },
    { en: "Heater", es: "Estufa" },
    { en: "Thermostat", es: "Termostato" },
    { en: "Electricity bill", es: "Factura de la luz" },
    { en: "Power cut", es: "Apagón" },
    { en: "Wrap up warm", es: "Abrígate bien" },
    { en: "Steamy window", es: "Ventana empañada" },
    { en: "Hot chocolate", es: "Chocolate caliente" },
    { en: "Chocolate with churros", es: "Chocolate con churros" },
    { en: "Soup", es: "Sopa" },
    { en: "Broth", es: "Caldo" },
    { en: "Chickpea stew", es: "Cocido" },
    { en: "Ski resort", es: "Estación de esquí" },
    { en: "Ski slope", es: "Pista de esquí" },
    { en: "Ski lift", es: "Remonte" },
    { en: "Chairlift", es: "Telesilla" },
    { en: "Ski pass", es: "Forfait" },
    { en: "Ski boots", es: "Botas de esquí" },
    { en: "Ski goggles", es: "Gafas de esquí" },
    { en: "Sledge / Sled", es: "Trineo" },
    { en: "Snowman", es: "Muñeco de nieve" },
    { en: "Snowball fight", es: "Guerra de bolas de nieve" },
    { en: "Ice skating", es: "Patinaje sobre hielo" },
    { en: "Ice rink", es: "Pista de hielo" },
    { en: "Snow-capped mountains", es: "Montañas nevadas" },
    { en: "Frozen lake", es: "Lago helado" },
    { en: "Snowdrift", es: "Ventisquero" },
    { en: "Snow day", es: "Día sin clase por nieve" },
    { en: "Snowed in", es: "Aislado por la nieve" },
    { en: "Snow chains", es: "Cadenas de nieve" },
    { en: "Snowplough / Snowplow", es: "Quitanieves" },
    { en: "The roads are icy", es: "Las carreteras están heladas" },
    { en: "To defrost the windscreen", es: "Descongelar el parabrisas" },
    { en: "Christmas", es: "Navidad" },
    { en: "Christmas Eve", es: "Nochebuena" },
    { en: "Merry Christmas!", es: "¡Feliz Navidad!" },
    { en: "Season's greetings", es: "Felices fiestas" },
    { en: "Christmas tree", es: "Árbol de Navidad" },
    { en: "Nativity scene", es: "Belén" },
    { en: "Fairy lights", es: "Guirnalda de luces" },
    { en: "Tinsel", es: "Espumillón" },
    { en: "Bauble", es: "Bola de Navidad" },
    { en: "Wreath", es: "Corona navideña" },
    { en: "Mistletoe", es: "Muérdago" },
    { en: "Advent calendar", es: "Calendario de adviento" },
    { en: "Wrapping paper", es: "Papel de regalo" },
    { en: "To wrap presents", es: "Envolver regalos" },
    { en: "Secret Santa", es: "Amigo invisible" },
    { en: "Christmas carol", es: "Villancico" },
    { en: "Christmas lottery", es: "Lotería de Navidad" },
    { en: "Nougat", es: "Turrón" },
    { en: "Marzipan", es: "Mazapán" },
    { en: "Gingerbread", es: "Pan de jengibre" },
    { en: "Candy cane", es: "Bastón de caramelo" },
    { en: "Reindeer", es: "Reno" },
    { en: "Santa Claus", es: "Papá Noel" },
    { en: "Family dinner", es: "Cena familiar" },
    { en: "Leftovers", es: "Sobras" },
    { en: "New Year's Eve", es: "Nochevieja" },
    { en: "The twelve grapes", es: "Las doce uvas" },
    { en: "Countdown", es: "Cuenta atrás" },
    { en: "Midnight toast", es: "Brindis de medianoche" },
    { en: "Cheers!", es: "¡Salud!" },
    { en: "Happy New Year!", es: "¡Feliz Año Nuevo!" },
    { en: "New Year's resolution", es: "Propósito de Año Nuevo" },
    { en: "A fresh start", es: "Borrón y cuenta nueva" },
    { en: "Three Kings' Day", es: "Día de Reyes" },
    { en: "Kings' parade", es: "Cabalgata de Reyes" },
    { en: "King cake", es: "Roscón de Reyes" },
    { en: "Winter sales", es: "Rebajas de invierno" },
    { en: "Gift receipt", es: "Ticket regalo" },
    { en: "To return something", es: "Devolver algo" },
    { en: "Christmas holidays", es: "Vacaciones de Navidad" },
    { en: "Report card", es: "Boletín de notas" },
    { en: "End of term", es: "Fin de trimestre" },
    { en: "Exam period", es: "Época de exámenes" },
    { en: "To cram", es: "Empollar" },
    { en: "Winter solstice", es: "Solsticio de invierno" },
    { en: "The shortest day", es: "El día más corto" },
    { en: "Long nights", es: "Noches largas" },
    { en: "Cabin fever", es: "Agobio por estar encerrado" },
    { en: "Flu season", es: "Temporada de gripe" },
    { en: "Fever", es: "Fiebre" },
    { en: "Cough syrup", es: "Jarabe para la tos" },
    { en: "To stay in bed", es: "Guardar cama" },
    { en: "Get well soon", es: "Que te mejores" },
    { en: "Valentine's Day", es: "San Valentín" },
    { en: "Carnival", es: "Carnaval" },
    { en: "Fancy dress party", es: "Fiesta de disfraces" },
    { en: "To hibernate", es: "Hibernar" },
    { en: "Winter wonderland", es: "Paisaje de cuento invernal" },
    { en: "To break the ice", es: "Romper el hielo" }
  ]
};
